title: "UBC Stat550 2021"
email: daniel@stat.ubc.ca
author: "Daniel J. McDonald"
author-url: https://dajmcdon.github.io/
description: > # this means to ignore newlines until "baseurl:"
  UBC Stat 550 - Techniques of Statistical Consulting, 2021
baseurl: "" # the subpath of your site, e.g.
url: "https://stat550-2021.github.io/"
remote_theme: dajmcdon/mkdocs-jekyll


# Social (First three Required)
repo: "https://github.com/stat550-2021/"
github_user: "stat550-2021"
github_repo: "stat550-2021"

# Image and (square) dimension for logo (don't start with /)
# If commented, will use material hat theme
# logo: "assets/img/logo/SRCC-square-red.png"
logo_width: 34
color: deep-purple # primary color for header, buttons

# Build settings
markdown: kramdown

tag_color: danger # danger, success, warning, primary, info, secondary



accentColor: orange # purple, green, etc.
themeColor: deep-purple # purple, green, blue, orange, purple, grey
fixedNav: true # true or false

permalink: /:title/
markdown: kramdown

toc:
  - title: Syllabus
    url: syllabus
  - title: Schedule
    url: schedule
  - title: Lecture slides
    url: lectures
  - title: Announcements
    url: announcements

